# frozen_string_literal: true

# Golden-vector tests for Campfire::RailsCompat against values generated by the
# real Rails reference app (ref-rust/vectors/*.json, Rails main / load_defaults
# 8.2). Run:
#
#   mise exec -- ruby -Ilib test/rails_compat_test.rb
#
# Override the vectors directory with RAILS_COMPAT_VECTORS=/path/to/vectors.
# A per-group pass/fail summary is printed after the run.

require "minitest/autorun"
require "json"
require_relative "../lib/campfire/rails_compat"

module RailsCompatVectors
  DIR = ENV.fetch("RAILS_COMPAT_VECTORS", File.expand_path("../../ref-rust/vectors", __dir__))
  COMPAT = JSON.parse(File.read(File.join(DIR, "rails_compat.json")))
  SESSIONS = JSON.parse(File.read(File.join(DIR, "campfire_sessions.json")))
  RUBY_CORE_PATH = File.join(DIR, "ruby_core.json")
  RUBY_CORE = File.exist?(RUBY_CORE_PATH) ? JSON.parse(File.read(RUBY_CORE_PATH)) : nil

  RESULTS = Hash.new { |h, k| h[k] = [0, 0, []] }
  SKIPPED = {}

  def self.record(group, ok, label)
    r = RESULTS[group]
    if ok
      r[0] += 1
    else
      r[1] += 1
      r[2] << label
    end
  end

  Minitest.after_run do
    puts "\nRailsCompat golden vectors (#{DIR}):"
    total_pass = total_fail = 0
    RESULTS.sort.each do |group, (pass, fail, labels)|
      total_pass += pass
      total_fail += fail
      puts format("  %-40s %4d/%-4d %s", group, pass, pass + fail, fail.zero? ? "ok" : "FAIL #{labels.first(5).inspect}")
    end
    puts format("  %-40s %4d/%-4d", "TOTAL", total_pass, total_pass + total_fail)
    SKIPPED.each { |group, why| puts "  skipped #{group}: #{why}" }
  end
end

class RailsCompatTest < Minitest::Test
  V = RailsCompatVectors
  RC = Campfire::RailsCompat
  SECRETS = RC::Secrets.new(V::COMPAT.fetch("secret_key_base"))
  ROTATED = RC::Secrets.new(V::COMPAT.fetch("rotated_secret_key_base"))
  NOW = Time.utc(2026, 1, 1, 12)


  def check(group, label, expected, actual)
    ok = expected == actual
    V.record(group, ok, label)
    if expected.nil?
      assert_nil actual, "#{group}: #{label}"
    else
      assert_equal expected, actual, "#{group}: #{label}"
    end
  end

  def vtime(s)
    return nil if s.nil?
    ns = RC::Util.parse_iso8601_ns(s) or raise "bad time #{s}"
    Time.at(ns / 1_000_000_000, ns % 1_000_000_000, :nsec, in: "UTC")
  end

  # ---- key generator / escaping ------------------------------------------

  def test_key_generator
    assert_equal NOW, vtime(V::COMPAT["now"])
    V::COMPAT["key_generator"].each do |c|
      check("key_generator", c["salt"], c["key_hex"], SECRETS.generate_key(c["salt"], c["length"]).unpack1("H*"))
    end
  end

  def test_cookie_escaping
    V::COMPAT["cookie_escaping"].each do |c|
      check("cookie_escaping", "escape #{c["raw"].inspect}", c["wire"], RC.escape_cookie(c["raw"])) if c["raw"]
      check("cookie_escaping", "unescape #{c["wire"].inspect}", c["parsed"], RC.unescape_cookie(c["wire"]))
    end
  end

  def test_rack_escape_ruby_core
    unless V::RUBY_CORE
      V::SKIPPED["rack_escape (ruby_core.json)"] = "file missing"
      skip "ruby_core.json missing"
    end
    V::RUBY_CORE["strings"].each do |c|
      next unless c["rack_escape"]
      check("rack_escape (ruby_core.json)", c["input"].inspect, c["rack_escape"], RC.escape_cookie(c["input"]))
    end
  end

  def test_cookie_header_parsing
    h = "a=1; session_token=x%2By; b=2; session_token=second; xsession_token=no"
    assert_equal "x+y", RC.cookie_value(h, "session_token")
    assert_equal RC.parse_cookie_header(h)["session_token"], RC.cookie_value(h, "session_token")
    assert_equal "1", RC.cookie_value(h, "a")
    assert_nil RC.cookie_value(h, "c")
    assert_nil RC.cookie_value("xsession_token=1", "session_token")
    assert_equal "2", RC.cookie_value("x=a;   session_token=2", "session_token")
    assert_nil RC.cookie_value(" session_token=2", "session_token") # Rack keeps the leading space in the key
    assert_equal({ " session_token" => "2" }, RC.parse_cookie_header(" session_token=2"))
    assert_equal "v ", RC.cookie_value("k=v ; z=1", "k")
    assert_equal "bad%zz", RC.cookie_value("k=bad%zz", "k")
    assert_equal "é", RC.cookie_value("q=é; k=é", "k")
    assert_equal "", RC.cookie_value("k=", "k")
    assert_nil RC.cookie_value(nil, "k")
  end

  # ---- signed cookies -----------------------------------------------------

  def test_signed_cookies_generate
    V::COMPAT["signed_cookies"]["generate"].each do |c|
      exp = vtime(c["expires_at"])
      raw = SECRETS.sign_cookie(c["name"], c["value"], expires: exp)
      check("signed_cookies.generate", c["value"].inspect, c["raw"], raw)
      header = RC.set_cookie_header(c["name"], raw, expires: exp, httponly: c["name"] == "session_token")
      check("signed_cookies.set_cookie", c["value"].inspect, c["set_cookie"], header)
    end
  end

  def test_permanent_expiry
    first = V::COMPAT["signed_cookies"]["generate"][0]
    assert_equal vtime(first["expires_at"]), SECRETS.permanent_expiry(NOW)
    assert_equal Time.utc(2100, 2, 28, 1), SECRETS.permanent_expiry(Time.utc(2080, 2, 29, 1))
    assert_equal Time.utc(2044, 2, 29, 1), SECRETS.permanent_expiry(Time.utc(2024, 2, 29, 1))
  end

  def test_signed_cookies_verify
    V::COMPAT["signed_cookies"]["verify"].each do |c|
      check("signed_cookies.verify", c["case"], c["expected"], SECRETS.verify_cookie(c["name"], c["raw"], now: vtime(c["now"])))
    end
  end

  # ---- encrypted cookies --------------------------------------------------

  def test_encrypted_cookies_generate
    V::COMPAT["encrypted_cookies"]["generate"].each do |c|
      label = "#{c["name"]} #{c["value"].inspect}"
      exp = vtime(c["expires_at"])
      plain = SECRETS.cookie_encryptor.decrypt(c["raw"])
      check("encrypted_cookies.plaintext", label, c["plaintext"], plain&.force_encoding("UTF-8"))
      ours = RC::Metadata.serialize_with_metadata(:null, RC::Util.as_json_encode(c["value"]), "cookie.#{c["name"]}", exp)
      check("encrypted_cookies.serialize", label, c["plaintext"], ours)
      raw = SECRETS.encrypt_cookie(c["name"], c["value"], expires: exp)
      check("encrypted_cookies.roundtrip", label, c["value"], SECRETS.decrypt_cookie(c["name"], raw, now: NOW))
      if c["set_cookie"]
        header = RC.set_cookie_header(c["name"], c["raw"], expires: exp)
        check("encrypted_cookies.set_cookie", label, c["set_cookie"], header)
      end
    end
  end

  def test_encrypted_cookies_verify
    V::COMPAT["encrypted_cookies"]["verify"].each do |c|
      check("encrypted_cookies.verify", c["case"], c["expected"], SECRETS.decrypt_cookie(c["name"], c["raw"], now: vtime(c["now"])))
    end
  end

  # ---- the real Rails session flow ---------------------------------------

  def test_rails_session
    s = V::COMPAT["session"]
    g = "session"
    wire = s["set_cookie"][/\A_campfire_session=([^;]*)/, 1]
    check(g, "set_cookie unescapes to raw", s["session_cookie_raw"], RC.unescape_cookie(wire))
    check(g, "cookie_value from header", s["session_cookie_raw"], RC.cookie_value("x=1; #{s["set_cookie"].split(";").first}", "_campfire_session"))
    check(g, "set_cookie attributes", s["set_cookie"], RC.set_cookie_header("_campfire_session", s["session_cookie_raw"], expires: SECRETS.permanent_expiry(NOW), httponly: true))
    session = SECRETS.decrypt_cookie("_campfire_session", s["session_cookie_raw"], now: NOW)
    check(g, "decrypt session", s["session"], session)
    check(g, "decrypt session after login", s["session_after_login"], SECRETS.decrypt_cookie("_campfire_session", s["session_after_login_raw"], now: NOW))

    token = s["session_token_value"]
    check(g, "verify session_token", token, SECRETS.verify_cookie("session_token", s["session_token_raw"], now: NOW))
    check(g, "sign session_token", s["session_token_raw"], SECRETS.sign_cookie("session_token", token, expires: SECRETS.permanent_expiry(NOW)))
    check(g, "session_token set_cookie", s["session_token_set_cookie"], RC.session_token_set_cookie(SECRETS, token, now: NOW))
  end

  # ---- forgery protection (Sec-Fetch-Site + Origin, no tokens) -------------

  def test_forgery_protection
    c = V::COMPAT["csrf"]
    check("csrf", "origin_check", c["forgery_protection_origin_check"], RC::CSRF::ORIGIN_CHECK)
    c["origin"].each do |o|
      expected = o["expected"] == "raises" ? false : o["expected"] # Rails raises InvalidAuthenticityToken -> same 422
      check("csrf.origin", "#{o["origin"].inspect} vs #{o["base_url"]}", expected, RC::CSRF.valid_request_origin?(o["origin"], o["base_url"]))
    end

    base = "https://campfire.example"
    assert RC::CSRF.valid_request?(nil, base, "same-origin", true)
    assert RC::CSRF.valid_request?(base, base, "same-site", true)
    refute RC::CSRF.valid_request?(base, base, "cross-site", true)
    refute RC::CSRF.valid_request?(base, base, "none", true), "a typed URL or bookmark doesn't write"
    refute RC::CSRF.valid_request?(nil, base, nil, true), "HTTPS writes need the header"
    assert RC::CSRF.valid_request?(nil, "http://campfire.example", nil, false), "plain HTTP falls back to SameSite=Lax and Origin"
    refute RC::CSRF.valid_request?("https://evil.example", base, "same-site", true), "the Origin check stays"
    refute RC::CSRF.valid_request?("null", base, "same-origin", true)
  end

  # ---- signed ids ---------------------------------------------------------

  def test_signed_ids
    V::COMPAT["signed_ids"]["generate"].each do |c|
      got = SECRETS.signed_id(c["model"], c["id"], purpose: c["purpose"], expires_at: vtime(c["expires_at"]))
      check("signed_ids.generate", "#{c["model"]} #{c["id"]} #{c["purpose"]} #{c["expires_at"]}", c["signed_id"], got)
    end
    V::COMPAT["signed_ids"]["verify"].each do |c|
      expected = c["expected"].is_a?(String) ? Integer(c["expected"]) : c["expected"]
      got = SECRETS.verify_signed_id(c["signed_id"], model_name: c["model"], purpose: c["purpose"], now: vtime(c["now"]))
      check("signed_ids.verify", c["case"], expected, got)
    end
  end

  # ---- global ids / sgids --------------------------------------------------

  def test_global_ids
    V::COMPAT["global_ids"].each do |c|
      gid = RC::GlobalID.parse(c["gid"])
      check("global_ids", c["gid"], [c["model_name"], c["id"], c["gid"], c["param"]], [gid.model_name, gid.id, gid.to_s, gid.to_param])
      check("global_ids", "from_param #{c["param"]}", c["gid"], RC::GlobalID.parse(c["param"])&.to_s)
      check("global_ids", "build #{c["gid"]}", c["gid"], RC::GID.build(c["model_name"], c["id"]).to_s)
    end
  end

  def test_sgids
    s = V::COMPAT["sgids"]
    assert_equal s["app"], RC::GlobalID::APP
    s["generate"].each do |c|
      gid = RC::GlobalID.parse(c["gid"])
      got = if c["data"].end_with?("?expires_in")
        SECRETS.attachable_sgid(gid.model_name, gid.id)
      else
        SECRETS.sgid(gid, purpose: c["purpose"], expires_at: vtime(c["expires_at"]))
      end
      check("sgids.generate", "#{c["data"]} for #{c["purpose"]}", c["sgid"], got)
    end
    s["verify"].each do |c|
      got = SECRETS.verify_sgid(c["sgid"], purpose: c["purpose"], now: vtime(c["now"]))
      check("sgids.verify", c["case"], c["expected"], got&.to_s)
    end
    # Forged with another secret: never located.
    %w[User Rooms::Open Account].each do |m|
      forged = ROTATED.sgid(RC::GID.build(m, 1), purpose: "attachable")
      assert_nil SECRETS.verify_sgid(forged, purpose: "attachable", now: NOW)
    end
  end

  # lib/rails_ext/action_text_attachables.rb. The DB lookup is stubbed with the
  # reference seed's users (ids 1 and 2). Where Rails raises we return nil.
  def test_unverified_sgids
    existing_users = %w[1 2]
    V::COMPAT["unverified_sgids"].each do |c|
      gid = SECRETS.attachable_gid_from_possibly_expired_sgid(c["sgid"])
      found = gid && existing_users.include?(gid.id) ? RC::GID.build(gid.model_name, gid.id).to_s : nil
      expected = c["expected"].is_a?(Hash) ? nil : c["expected"]
      check("unverified_sgids", c["case"], expected, found)
    end
  end

  # ---- Turbo ---------------------------------------------------------------

  def test_turbo_stream_names
    t = V::COMPAT["turbo_stream_names"]
    t["generate"].each do |c|
      check("turbo_stream_names.generate", c["stream_name"], c["signed"], SECRETS.signed_stream_name(*c["parts"]))
      check("turbo_stream_names.generate", "joined #{c["stream_name"]}", c["signed"], SECRETS.signed_stream_name(c["stream_name"]))
    end
    t["verify"].each do |c|
      check("turbo_stream_names.verify", c["case"], c["expected"], SECRETS.verified_stream_name(c["signed"]))
    end
  end

  # ---- app verifiers (ActiveStorage) ---------------------------------------

  def test_app_verifiers
    a = V::COMPAT["app_verifiers"]
    a["generate"].each do |c|
      got = SECRETS.app_verifier(c["name"]).generate_raw(c["data_json"], purpose: c["purpose"], expires_at: vtime(c["expires_at"]))
      check("app_verifiers.generate", "#{c["name"]} #{c["data_json"]}", c["message"], got)
      if c["data_json"] !~ /[{\[]/ # scalar data: generate from the Ruby value too
        got2 = SECRETS.app_verifier(c["name"]).generate(JSON.parse(c["data_json"]), purpose: c["purpose"], expires_at: vtime(c["expires_at"]))
        check("app_verifiers.generate", "value #{c["data_json"]}", c["message"], got2)
      end
    end
    a["verify"].each do |c|
      ok, value = SECRETS.app_verifier(c["name"]).verified_pair(c["message"], purpose: c["purpose"], now: vtime(c["now"]))
      check("app_verifiers.verify", c["case"], c["expected_json"], ok ? RC::Util.as_json_encode(value) : nil)
    end
  end

  # ---- campfire_sessions.json (seeded app) ---------------------------------

  def test_campfire_sessions
    g = "campfire_sessions"
    V::SESSIONS["sessions"].each do |s|
      check(g, "cookie_value #{s["user_name"]}", s["token"], SECRETS.verify_cookie("session_token", s["cookie_value"]))
      raw = RC.cookie_value("foo=bar; #{s["cookie_header"]}; last_room=3", "session_token")
      check(g, "cookie_header #{s["user_name"]}", s["token"], SECRETS.verify_cookie("session_token", raw))
      check(g, "rotated secret rejects #{s["user_name"]}", nil, ROTATED.verify_cookie("session_token", s["cookie_value"]))
    end
    V::SESSIONS["blobs"].each do |b|
      check(g, "blob signed_id #{b["blob_id"]}", b["blob_id"], SECRETS.app_verifier("ActiveStorage").verified(b["signed_id"], purpose: "blob_id"))
      check(g, "blob redirect path #{b["blob_id"]}", b["signed_id"], b["redirect_path"].split("/")[-2])
    end
    f = V::SESSIONS["forged"]
    check(g, "forged token (valid signature, unknown token)", "not-a-session-token",
      SECRETS.verify_cookie("session_token", RC.cookie_value(f["cookie_header"], "session_token")))
  end

  def test_passwords_not_applicable
    V::SKIPPED["passwords"] = "bcrypt digests are out of scope for RailsCompat (#{V::COMPAT["passwords"]["checks"].size} checks)"
    skip "bcrypt is not part of RailsCompat"
  end

  # ---- Ractors -----------------------------------------------------------

  def test_all_constants_shareable
    walk = lambda do |mod|
      mod.constants(false).each do |c|
        v = mod.const_get(c, false)
        if v.is_a?(Module)
          walk.(v) if v.name&.start_with?("Campfire::RailsCompat")
        else
          check("ractor", "#{mod}::#{c} shareable", true, Ractor.shareable?(v))
        end
      end
    end
    walk.(Campfire::RailsCompat)
  end

  def test_shareable_and_usable_from_ractors
    assert Ractor.shareable?(SECRETS)
    vec = V::COMPAT
    signed_raw = Ractor.make_shareable(vec["signed_cookies"]["generate"][0]["raw"].dup)
    enc_raw = Ractor.make_shareable(vec["encrypted_cookies"]["generate"][0]["raw"].dup)
    secrets = SECRETS
    r = Ractor.new(secrets, signed_raw, enc_raw) do |s, sr, er|
      now = Time.utc(2026, 1, 1, 12)
      fresh = s.sign_cookie("session_token", "abc", expires: s.permanent_expiry(now))
      enc = s.encrypt_cookie("_campfire_session", { "a" => 1 }, expires: s.permanent_expiry(now))
      sid = s.signed_id("User", 7, purpose: "avatar")
      [
        s.verify_cookie("session_token", sr, now: now),
        s.verify_cookie("session_token", fresh, now: now),
        s.decrypt_cookie("_campfire_session", er, now: now),
        s.decrypt_cookie("_campfire_session", enc, now: now),
        Campfire::RailsCompat::CSRF.valid_request?("https://a.example", "https://a.example", "same-origin", true),
        s.verify_signed_id(sid, model_name: "User", purpose: "avatar", now: now),
        s.verified_stream_name(s.signed_stream_name("rooms")),
        s.verify_sgid(s.attachable_sgid("User", 1), purpose: "attachable", now: now).to_s,
        Campfire::RailsCompat.cookie_value("a=1; session_token=x%2By", "session_token"),
        Campfire::RailsCompat.escape_cookie("a+b/c=d é"),
        Campfire::RailsCompat::GlobalID.attachable_gid_from_possibly_expired_sgid(s.attachable_sgid("User", 2)).to_s
      ]
    end
    got = r.value
    expected = [
      vec["signed_cookies"]["generate"][0]["value"], "abc",
      vec["encrypted_cookies"]["generate"][0]["value"], { "a" => 1 },
      true, 7, "rooms", "gid://campfire/User/1?expires_in", "x+y",
      "a%2Bb%2Fc%3Dd+%C3%A9", "gid://campfire/User/2?expires_in"
    ]
    got.zip(expected).each_with_index { |(g, e), i| check("ractor", "result ##{i}", e, g) }
  end
end

